fix issue where unique name is not unique during testing because of the static variable
WEIRD FACT
* rust tests are passed in parallel
* so the static var gets shared in parallel
* ..... :(

> cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running target/debug/deps/rc-a55be7b3b4ed7934

running 20 tests
test rco::rco_test::unique_name_test ... ok
test rco::rco_test::unique_name_reset_test ... ok
test test_helpers::test_list ... ok
test test_helpers::test_vecdec ... ok
test parser::r1::test_private_parse_expr ... ok
test testing::integration_tests::test_tokenizer_with_parser ... ok
test testing::parser_tests::test_add ... ok
test rco::rco_test::test_nested_negation ... FAILED
test rco::rco_test::test_nested_negation_addition ... FAILED
test testing::parser_tests::test_add_with_negative ... ok
test testing::parser_tests::test_let ... ok
test testing::tokenizer_tests::test_full_program ... ok
test testing::parser_tests::test_nested_add ... ok
test testing::tokenizer_tests::test_add ... ok
test testing::tokenizer_tests::test_let ... ok
test testing::parser_tests::test_let_2 ... ok
test testing::uniquify_tests::test_add ... ok
test testing::uniquify_tests::test_shadow ... ok
test testing::uniquify_tests::test_shadow_inside_value ... ok
test testing::uniquify_tests::test_single_let ... ok

failures:

---- rco::rco_test::test_nested_negation stdout ----
thread 'rco::rco_test::test_nested_negation' panicked at 'assertion failed: `(left == right)`
  left: `List([Binding { var: Var("tmp9"), val: List([Negation, Num(2)]) }, List([Negation, Var("tmp9")])])`,
 right: `List([Binding { var: Var("tmp1"), val: List([Negation, Num(2)]) }, List([Negation, Var("tmp1")])])`', src/rco.rs:141:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- rco::rco_test::test_nested_negation_addition stdout ----
thread 'rco::rco_test::test_nested_negation_addition' panicked at 'assertion failed: `(left == right)`
  left: `List([Binding { var: Var("tmp9"), val: List([Binding { var: Var("tmp11"), val: List([Negation, Num(4)]) }, List([Binding { var: Var("tmp10"), val: List([Negation, Num(3)]) }, List([Plus, Var("tmp10"), Var("tmp11")])])]) }, List([Negation, Var("tmp9")])])`,
 right: `List([Binding { var: Var("tmp1"), val: List([Binding { var: Var("tmp3"), val: List([Negation, Num(4)]) }, List([Binding { var: Var("tmp2"), val: List([Negation, Num(3)]) }, List([Plus, Var("tmp2"), Var("tmp3")])])]) }, List([Negation, Var("tmp1")])])`', src/rco.rs:174:9

failures:
    rco::rco_test::test_nested_negation
    rco::rco_test::test_nested_negation_addition

test result: FAILED. 18 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--bin rc'
>

Co-Authored-By: johnvtan <johnvtan@users.noreply.github.com>