fixed that error
interesting that uniq handles if through the `[(op es ...)]` case

--------------------------------------

new error is RCO

> ./run programs/if-should-exit-42.rc
match: no matching clause for #f
  location...:
   src/rco.rkt:61:2
  context...:
   /Applications/Racket v7.3/collects/racket/match/runtime.rkt:24:0: match:error
   /Users/mfekadu/GitHub/rc/src/rco.rkt:50:7: for-loop
   /Applications/Racket v7.3/collects/racket/match/compiler.rkt:507:40: f46
   /Users/mfekadu/GitHub/rc/src/rco.rkt:60:0: rco-arg
   /Users/mfekadu/GitHub/rc/src/rco.rkt:50:7: for-loop
   /Applications/Racket v7.3/collects/racket/match/compiler.rkt:507:40: f46
   /Users/mfekadu/GitHub/rc/src/rco.rkt:10:0: rco-prog
   "/Users/mfekadu/GitHub/rc/compiler.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    do_stuff()
  File "build.py", line 24, in do_stuff
    subprocess.run(compile_args, stdout=output, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./compiler.rkt', 'programs/if-should-exit-42.rc']' returned non-zero exit status 1.
>

Co-Authored-By: johnvtan <johnvtan@users.noreply.github.com>