fix an error where ec_funcs dont handle #f nor (read)
is check-match greedy ¯\_(ツ)_/¯

====================

TODO:

> ./run programs/if-should-exit-42.rc
oh no
  context...:
   "/Users/mfekadu/GitHub/rc/compiler.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    do_stuff()
  File "build.py", line 24, in do_stuff
    subprocess.run(compile_args, stdout=output, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./compiler.rkt', 'programs/if-should-exit-42.rc']' returned non-zero exit status 1.
> vim compiler.rkt
> code .
>

Co-Authored-By: johnvtan <johnvtan@users.noreply.github.com>