fix the tests to follow R1 grammar and fix bug in test1 where the nested let was missing a body
> python3 build.py programs/test1.rc
>
> ./a.out
> echo $?
255
>
> racket
Welcome to Racket v7.3.
> (let ([x 2]) (let ([y 3]) (+ x (- y))))
-1
> ^D
>
>
> python3 build.py programs/test2.rc
>
> ./a.out
>
> echo $?
4
> racket
Welcome to Racket v7.3.
> (let ([x 2]) (+ x 2))
4
> ; user break [,bt for context]
^D
>
> python3 build.py programs/test3.rc
programs/test3.rc::3: read: expected a `)` to close `(`
  context...:
   read-one/not-eof
   loop
   [repeats 2 more times]
   read-unwrapped-sequence17
   read-undotted
   read-one/not-eof
   loop
   read-unwrapped-sequence17
   read-undotted
   read-one/not-eof
   loop
   read-unwrapped-sequence17
   read-undotted
   read32
   read
   "/Users/mfekadu/GitHub/rc/racket/compiler.rkt": [running body]
   ...
Traceback (most recent call last):
  File "build.py", line 23, in <module>
    subprocess.run(compile_args, stdout=output, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./compiler.rkt', 'programs/test3.rc']' returned non-zero exit status 1.
>

Co-Authored-By: johnvtan <johnvtan@users.noreply.github.com>